In [2]:
import numpy as np

In [3]:
a = np.array([3,4,5])

In [4]:
b = np.array([1, 3, 6])

In [5]:
print(np.dot(a,b))

45


In [7]:
x = np.matrix([[1,2,3,4], [5,6,7,8], [2,3,4,5], [6,7,8,9]])

In [8]:
x

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 3, 4, 5],
        [6, 7, 8, 9]])

In [9]:
x.shape

(4, 4)

In [10]:
a = np.matrix([[1,4,5], [2,4,3], [5,6,8]])

In [11]:
a

matrix([[1, 4, 5],
        [2, 4, 3],
        [5, 6, 8]])

In [12]:
a.shape

(3, 3)

In [13]:
b = np.matrix([[2], [4], [5]])

In [14]:
b.shape

(3, 1)

In [15]:
print(a*b)

[[43]
 [35]
 [74]]


In [16]:
print(b*a)

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [17]:
from numpy import linalg as LA

In [18]:
x = np.matrix([[1,3,1], [2,2,1], [3,5,3]])

In [19]:
x

matrix([[1, 3, 1],
        [2, 2, 1],
        [3, 5, 3]])

In [20]:
x.shape

(3, 3)

In [21]:
LA.matrix_rank(x)

3